# NB: this file was automatically generated by Dynare
#     from qpm_simpl_conv.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(17, 11);
gp = zeros(17, 17, 11);
end
return (rp, gp)
end
