ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	34
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	35
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	36
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	37
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	38
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	39
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	40
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	41
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	42
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	43
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	44
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	45
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	46
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	47
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	48
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	49
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	50
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	51
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	52
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	53
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	54
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	55
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	56
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	57
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	58
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	59
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	60
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	61
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	62
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	63
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	64
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	65
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	66

