FUNCTION CHECK_BONDS(PAR, SIZEPAR,PARBOUDS,DIST)
  IMPLICIT NONE 
  INTEGER SIZEPAR
  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(12, 60)
  REAL(DP) , DIMENSION(SIZEPAR) , INTENT(IN) :: PAR
  REAL(DP), DIMENSION(SIZEPAR,2), INTENT(IN) :: PARBOUDS
  REAL(DP), INTENT(OUT) :: DIST
!  INTEGER, DIMENSION(SIZEPAR), INTENT(IN) :: PARIND
!  INTEGER, INTENT(IN) :: NPAR
  INTEGER i , CHECK_BONDS
  
  CHECK_BONDS = 0
  DIST = 0.0
  DO I = 1, SIZEPAR
    ! print *, PARBOUDS(I,1), PARBOUDS(I,2), PAR(I)
     IF (  PAR(I) .LT. PARBOUDS(I,1)  ) THEN
        print *, PARBOUDS(I,1), PARBOUDS(I,2), PAR(I), I
        CHECK_BONDS = 1
        DIST = DIST + ABS(PAR(I) - PARBOUDS(I,1))
        !print *, CHECK_BONDS
        !stop
     ELSEIF ( PAR(I) .GT. PARBOUDS(I,2)) THEN
        print *, PARBOUDS(I,1), PARBOUDS(I,2), PAR(I), I
        CHECK_BONDS = 1
        DIST = DIST + ABS(PAR(I) - PARBOUDS(I,2))
     END IF
  END DO
  
  !print *
END FUNCTION CHECK_BONDS
