SUBROUTINE KALMANFILTERMATRICES(F, P, NUM_K, NUM_EXO, NUM_CNTRL_OBS,R, T)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NUM_K, NUM_EXO, NUM_CNTRL_OBS
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_CNTRL_OBS,NUM_K) :: F
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_K,NUM_K) :: P
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_CNTRL_OBS+NUM_K,NUM_CNTRL_OBS+NUM_K) :: T
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_CNTRL_OBS+NUM_K,NUM_EXO) :: R
  INTEGER :: NUM_EST,N_K, N_EX, K_EX,J
  NUM_EST=NUM_CNTRL_OBS+NUM_K
  N_K=NUM_EST - NUM_K
  N_EX=NUM_EST - NUM_EXO
  K_EX=NUM_K - NUM_EXO

  T(1:N_K,1+N_K:N_EX)=F(:,1:K_EX)

  CALL DGEMM('N','N',N_K,NUM_EXO,NUM_EXO,DBLE(1.0),F(:,K_EX+1:NUM_K),N_K,&
       & P(K_EX+1:NUM_K,K_EX+1:NUM_K),NUM_EXO,DBLE(0.0),&
       & T(1:N_K,1+N_EX:NUM_EST),N_K)

  T(1+N_K:N_EX,N_K+1:N_EX)=P(1:NUM_K-NUM_EXO,1:NUM_K-NUM_EXO)
  CALL DGEMM('N','N',K_EX,NUM_EXO,NUM_EXO,DBLE(1.0),P(1:K_EX,K_EX+1:NUM_K),K_EX,&
       &P(K_EX+1:NUM_K,K_EX+1:NUM_K),NUM_EXO,DBLE(0.0),&
       &T(1+N_K:N_EX,1+N_EX:NUM_EST),K_EX)
  T(1+N_EX:NUM_EST,1+N_EX:NUM_EST)=P(K_EX+1:NUM_K,K_EX+1:NUM_K)
  T(1:NUM_EST,1:N_K)=0.0
  T(1+N_EX:NUM_EST,N_K+1:N_EX)=0.0

  R(1:N_K,1:NUM_EXO)=F(:,K_EX+1:NUM_K)
  R(N_K+1:N_EX,1:NUM_EXO) = P(1:K_EX,K_EX+1:NUM_K)
  R(N_EX+1:NUM_EST,1:NUM_EXO)=0.0
  
  DO J=1,int(NUM_EXO)    
     R(N_EX+J, J)=1.0
  END DO

END SUBROUTINE KALMANFILTERMATRICES

SUBROUTINE OBSCONTROLKALMAN(F,F_OBS)
  USE MODEL_CONST_MOD
  USE LIKELIHOOD_CONST_MOD, ONLY : ZIND
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_N-NUM_K,NUM_K) :: F
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_CNTRL_OBS,NUM_K) :: F_OBS
  F_OBS=F(ZIND,:)
END SUBROUTINE


