! FAST KALMAN FILTER - KOOPMAN AND DURBIN (2000)
! Codigo escrito por Pietro Bonaldi y modificado por Luis Rojas
SUBROUTINE FAST_KAL_FILT_PAT_LA(Z,H,T,R,Q,Y,A_INI,P_INI,NUM_OBS,NUM_EST,NUM_K,NUM_DIST_EST,NUM_PER,LOG_L,FOR_PERIOD,A_T,P_T)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NUM_OBS, NUM_EST, NUM_DIST_EST, NUM_PER, NUM_K, FOR_PERIOD
  INTEGER, INTENT(IN), DIMENSION(NUM_OBS) :: Z
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_OBS) :: H !SINCE H IS DIAGONAL, JUST THE CORRESPONDING VECTOR IS NEEDED
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST,NUM_EST) :: T,P_INI
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST,NUM_DIST_EST) :: R
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_DIST_EST,NUM_DIST_EST) :: Q
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_OBS,NUM_PER) :: Y
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST) :: A_INI
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_EST) :: A_T
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_EST,NUM_EST) :: P_T
  DOUBLE PRECISION, INTENT(OUT) :: LOG_L
  INTEGER :: I, J, COL_T, N_K, zi
  
  DOUBLE PRECISION, DIMENSION(NUM_EST) :: A_I, A_TEMP
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: P_I
  
  
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_DIST_EST) :: RQ
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: RQRT

  DOUBLE PRECISION :: V, F
  DOUBLE PRECISION, DIMENSION(NUM_EST) :: K
  DOUBLE PRECISION, DIMENSION(NUM_EST-NUM_K,NUM_K) :: T1P4
  DOUBLE PRECISION, DIMENSION(NUM_K,NUM_K) :: T2P4


 
  A_I=A_INI
  P_I=P_INI
  CALL DGEMM('N','N',NUM_EST,NUM_DIST_EST,NUM_DIST_EST,DBLE(1.0),R,NUM_EST,Q,NUM_DIST_EST,DBLE(0.0),RQ,NUM_EST)  !RQ=R*Q
  CALL DGEMM('N','T',NUM_EST,NUM_EST,NUM_DIST_EST,DBLE(1.0),RQ,NUM_EST,R,NUM_EST,DBLE(0.0),RQRT,NUM_EST)  !RQRT=R*Q*R'
  LOG_L=0.0

  DO J=1, FOR_PERIOD
     DO I=1, NUM_OBS
           zi = Z(I)
           V= Y(I,J)- A_I(zi)
           K=P_I(1:NUM_EST,zi)
           F=P_I(zi,zi)+H(I)
           A_I=A_I + (K/dble(F))*V    
           CALL DGEMM('N', 'T', NUM_EST, NUM_EST, int(1), dble(-1.0/F) ,K,NUM_EST, K, NUM_EST, dble(1.0), P_I, NUM_EST)
        LOG_L=LOG_L+0.5*(LOG(F)+(V**2)/dble(F))      
       ! print *,"log=",log_l
     END DO
    
     A_TEMP=A_I 
     !MDIM = NUM_EST
     !PDIM = NUM_OBS
     !RDIM = NUM_DIST_EST
     !NDIM = NUM_PER
     COL_T=1+NUM_EST-NUM_K
     N_K=NUM_EST-NUM_K  
     CALL DGEMV('N',NUM_EST,NUM_K,DBLE(1.0),&
          &T(1:NUM_EST,COL_T:NUM_EST),NUM_EST,&
          &A_TEMP(COL_T:NUM_EST),INT(1),DBLE(0.0),A_I,INT(1))       
          
     CALL DGEMM('N','N',N_K,NUM_K,NUM_K,DBLE(1.0),T(1:N_K,COL_T:NUM_EST),N_K,&
          &P_I(COL_T:NUM_EST,COL_T:NUM_EST),NUM_K,DBLE(0.0),T1P4,N_K)

     CALL DGEMM('N','N',NUM_K,NUM_K,NUM_K,DBLE(1.0),T(N_K+1:NUM_EST,COL_T:NUM_EST),NUM_K,&
          &P_I(COL_T:NUM_EST,COL_T:NUM_EST),NUM_K,DBLE(0.0),T2P4,NUM_K)
     
     CALL DGEMM('N','T',N_K,N_K,NUM_K,DBLE(1.0),T1P4,N_K,&
          &T(1:N_K,COL_T:NUM_EST),N_K,DBLE(0.0),P_I(1:N_K,1:N_K),N_K) 

     CALL DGEMM('N','T',N_K,NUM_K,NUM_K,DBLE(1.0),T1P4,N_K,&
          &T(N_K+1:NUM_EST,COL_T:NUM_EST),NUM_K,DBLE(0.0),P_I(1:N_K,N_K+1:NUM_EST),N_K)
     P_I(N_K+1:NUM_EST,1:N_K)=TRANSPOSE(P_I(1:N_K,N_K+1:NUM_EST))
     CALL DGEMM('N','T',NUM_K,NUM_K,NUM_K,DBLE(1.0),T2P4,NUM_K,&
          &T(N_K+1:NUM_EST,COL_T:NUM_EST),NUM_K,DBLE(0.0),P_I(N_K+1:NUM_EST,N_K+1:NUM_EST),NUM_K)
     P_I=P_I+RQRT    
     IF (J .EQ. FOR_PERIOD) THEN
     A_T=A_I
     P_T=P_I
  END DO
END SUBROUTINE FAST_KAL_FILT_PAT_LA
     
