! FAST KALMAN FILTER - KOOPMAN AND DURBIN (2000)
! Codigo escrito por Pietro Bonaldi
SUBROUTINE FAST_KAL_FILT(Z,H,T,R,Q,Y,A_INI,P_INI,NUM_OBS,NUM_EST,NUM_DIST_EST,NUM_PER,LOG_L)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NUM_OBS, NUM_EST, NUM_DIST_EST, NUM_PER
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_OBS,NUM_EST) :: Z
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_OBS) :: H !SINCE H IS DIAGONAL, JUST THE CORRESPONDING VECTOR IS NEEDED
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST,NUM_EST) :: T,P_INI
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST,NUM_DIST_EST) :: R
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_DIST_EST,NUM_DIST_EST) :: Q
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_OBS,NUM_PER) :: Y
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST) :: A_INI
  DOUBLE PRECISION, INTENT(OUT) :: LOG_L
  INTEGER :: I, J
  
  DOUBLE PRECISION, DIMENSION(NUM_EST) :: A_I, A_TEMP
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: P_I
  
  
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_DIST_EST) :: RQ
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: RQRT

  DOUBLE PRECISION :: V, F
  DOUBLE PRECISION, DIMENSION(NUM_EST) :: K
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: TPTT

  DOUBLE PRECISION DDOT
  EXTERNAL DDOT
  
  
  A_I=A_INI
  P_I=P_INI
  CALL DGEMM('N','N',NUM_EST,NUM_DIST_EST,NUM_DIST_EST,DBLE(1.0),R,NUM_EST,Q,NUM_DIST_EST,DBLE(0.0),RQ,NUM_EST)  !RQ=R*Q
  CALL DGEMM('N','T',NUM_EST,NUM_EST,NUM_DIST_EST,DBLE(1.0),RQ,NUM_EST,R,NUM_EST,DBLE(0.0),RQRT,NUM_EST)  !RQRT=R*Q*R'
  LOG_L=0.0

  DO J=1, NUM_PER
     DO I=1, NUM_OBS
        
        V= Y(I,J) - DDOT(NUM_EST,Z(I,1:NUM_EST),INT(1),A_I,INT(1)) 
        !CALL DGEMV('N',NUM_EST,NUM_EST,DBLE(1.0),P_I,NUM_EST,Z(I,1:NUM_EST),INT(1),DBLE(0.0),K,INT(1))        
        !cambiar por
        CALL DSYMV ( 'U', NUM_EST, dble(1.0), P_I, NUM_EST, Z(I,1:NUM_EST), int(1), dble(0.0), K, INT(1) )
        
        F=DDOT(NUM_EST,Z(I,1:NUM_EST),int(1),K,int(1)) +H(I)
        
        A_I=A_I + (K/dble(F))*V 
        
        CALL DGEMM('N', 'T', NUM_EST, NUM_EST, int(1), dble(-1.0/F) ,K,NUM_EST, K, NUM_EST, dble(1.0), P_I, NUM_EST)
        LOG_L=LOG_L+0.5*(LOG(F)+(V**2)/dble(F))
        
     END DO
     A_TEMP=A_I
     
     !En estos pasos pueden mejorar
     !Estas instrucciones estan correcta
     CALL DGEMV('N',NUM_EST,NUM_EST,DBLE(1.0),T,NUM_EST,A_TEMP,INT(1),DBLE(0.0),A_I,INT(1))       
     CALL DGEMM('N','N',NUM_EST,NUM_EST,NUM_EST,DBLE(1.0),T,NUM_EST,P_I,NUM_EST,DBLE(0.0),TPTT,NUM_EST)  !TPTT=T*P_I
     P_I=RQRT
     CALL DGEMM('N','T',NUM_EST,NUM_EST,NUM_EST,DBLE(1.0),TPTT,NUM_EST,T,NUM_EST,DBLE(1.0),P_I,NUM_EST) !TPTT=T*P_I*T' 

     !MDIM = NUM_EST
     !PDIM = NUM_OBS
     !RDIM = NUM_DIST_EST
     !NDIM = NUM_PER
     
!      CALL DGEMV('N',NUM_EST,INT(9),DBLE(1.0),&
!           &T(1:NUM_EST,(1+NUM_EST-9):NUM_EST),NUM_EST,&
!           &A_TEMP((1+NUM_EST-9):NUM_EST),INT(1),DBLE(0.0),A_I,INT(1))       
     
!      CALL DGEMM('N','N',NUM_EST,NUM_EST,NUM_EST,DBLE(1.0),T,NUM_EST,P_I,NUM_EST,DBLE(0.0),TPTT,NUM_EST)  !TPTT=T*P_I
!      P_I=RQRT
!      CALL DGEMM('N','T',NUM_EST,NUM_EST,NUM_EST,DBLE(1.0),TPTT,NUM_EST,T,NUM_EST,DBLE(1.0),P_I,NUM_EST) !TPTT=T*P_I*T' 
     

  END DO
END SUBROUTINE FAST_KAL_FILT
     
