SUBROUTINE FCNSA(VP, NEQ,  OUTOBJ)    

  INTEGER NEQ
  DOUBLE PRECISION VP(NEQ),FVEC(NEQ), OUTOBJ
  external FCNHYD

  CALL FCNHYD(NEQ,VP,FVEC,INT(1))   
  
  OUTOBJ = DBLE(NEQ)*SUM(FVEC**2)
  
  !  if (ISNAN(OUTOBJ)) then
  !     OUTOBJ
END SUBROUTINE FCNSA
