SUBROUTINE KALMANSIMUL_LA(Z,T, A0, NDIM,PDIM, MDIM, Y, A)
  IMPLICIT NONE 
  ! ESTE METODO DE SIMULACIÓN ES PARA MODELOS EN LOS CUALES LOS CHOQUES
  ! DE LA ECUACIÓN DE TRANSICIÓN ES INDEPENDENDIENTE DE LA ECUAC
  ! CION DE MEDIDA. 
  ! Y_T = Z*A_T + E_T E_T\SIM N(0, H)
  ! A_T+1 = T*A_T + R*\ETA_T \ETA_T \SIM N(0, Q)
  ! T = 1,...,NSAMPLE

  ! ARCHIVO MODIFICADO POR LUIS ROJAS. AHORA ES PARA PRONOSTICO

  
  INTEGER, INTENT(IN) ::  NDIM, PDIM, MDIM
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(MDIM, NDIM+1) :: A  ! A = ( A0,..., A(N+1)) 
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(PDIM, NDIM)::  Y
    
  DOUBLE PRECISION, INTENT(IN), DIMENSION(MDIM, MDIM) :: T
  DOUBLE PRECISION, INTENT(IN), DIMENSION(PDIM, MDIM) :: Z
  DOUBLE PRECISION, INTENT(IN), DIMENSION(MDIM) :: A0  
  
  INTEGER i,j
  
  
  
     
  A(:,1) = A0
  DO I = 1, NDIM
     CALL DGEMV('N',MDIM,MDIM, dble(1),T, MDIM,A(:,I),int(1.0),dble(1.0), A(:,I+1),int(1.0))     
  END DO
  
  CALL DGEMM('N','N',PDIM,NDIM,MDIM,DBLE(1.0),Z,PDIM,A(:, 1:NDIM),MDIM,DBLE(1.0),Y,PDIM)     
  !ITERAR LA 
END SUBROUTINE KALMANSIMUL_LA
