SUBROUTINE KALMANSIMUL(Z,T,H,R,Q, A0, ET, ETA, NDIM,PDIM, MDIM, RDIM, Y, A, INFO )
  IMPLICIT NONE 
  ! ESTE METODO DE SIMULACIÓN ES PARA MODELOS EN LOS CUALES LOS CHOQUES
  ! DE LA ECUACIÓN DE TRANSICIÓN ES INDEPENDENDIENTE DE LA ECUAC
  ! CION DE MEDIDA. 
  ! Y_T = Z*A_T + E_T E_T\SIM N(0, H)
  ! A_T+1 = T*A_T + R*\ETA_T \ETA_T \SIM N(0, Q)
  ! T = 1,...,NSAMPLE
  
  INTEGER, INTENT(IN) ::  NDIM, PDIM, MDIM, RDIM
  INTEGER, INTENT(IN) ::  INFO
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(MDIM, NDIM+1) :: A  ! A = ( A0,..., A(N+1))
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(PDIM, NDIM)::  Y
    
  DOUBLE PRECISION, INTENT(IN), DIMENSION(MDIM, MDIM) :: T
  DOUBLE PRECISION, INTENT(IN), DIMENSION(PDIM, MDIM) :: Z
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(MDIM, RDIM) :: R
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(RDIM, RDIM) :: Q
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(PDIM, PDIM) :: H
  DOUBLE PRECISION, INTENT(IN), DIMENSION(MDIM) :: A0  
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(RDIM, NDIM) :: ETA
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(PDIM, NDIM) :: ET
  
  INTEGER i,j
  DOUBLE PRECISION, DIMENSION(PDIM, PDIM) :: HCHOL   
  DOUBLE PRECISION, DIMENSION(MDIM, NDIM) :: ETARQ
  DOUBLE PRECISION, DIMENSION(MDIM, RDIM) :: RQ
  DOUBLE PRECISION,  DIMENSION(PDIM, NDIM) :: ETH
  DOUBLE PRECISION,  DIMENSION(RDIM, NDIM) :: ETAR
  
  
  !! TRANSFORMA LOS CHOQUES
  !! CALCULA LA CHOLESKY
  HCHOL = H
  CALL DPOTRF('L', PDIM, HCHOL, PDIM, INFO)
  IF (INFO .NE.0) THEN 
     PRINT *, "DESCOMPOSICION DE CHOLESKY DE H FALLO" 
     RETURN
  END IF
  
  CALL DSYMM('L','L',PDIM,NDIM,DBLE(1.0),HCHOL,PDIM, ET, PDIM, DBLE(0.0), ETH, PDIM)       
  
  !CALCULA LA CHOLESKY DE Q
  CALL DPOTRF('L', RDIM, Q, RDIM, INFO)
  IF (INFO .NE.0) THEN 
     PRINT *, "DESCOMPOSICION DE CHOLESKY DE Q FALLO" 
     RETURN
  END IF
  
  CALL DSYMM('L','L',RDIM,NDIM,DBLE(1.0),Q,RDIM, ETA, RDIM, DBLE(0.0), ETAR, RDIM)           
  CALL DGEMM('N','N',MDIM,NDIM,RDIM,DBLE(1.0),R, MDIM,ETAR,RDIM,DBLE(0.0),ETARQ,MDIM)
    
  A(:,1) = A0
  DO I = 1, NDIM
     A(:,I+1) = ETARQ(:,I)        
     CALL DGEMV('N',MDIM,MDIM, dble(1),T, MDIM,A(:,I),int(1.0),dble(1.0), A(:,I+1),int(1.0))     
  END DO
  
  Y = ETH 
  CALL DGEMM('N','N',PDIM,NDIM,MDIM,DBLE(1.0),Z,PDIM,A(:, 1:NDIM),MDIM,DBLE(1.0),Y,PDIM)     
  !ITERAR LA 
END SUBROUTINE KALMANSIMUL
