SUBROUTINE MCMCMODEL(MC, C_SCALE, SIGMA_DRAWS, PARINI,SIZEPAR, ACCEPT, DRAWS)
  USE RANDOM
  USE PARAMETER_VECTOR_MOD, ONLY: PARBOUNDS, PARIND 
  USE PRIOR_MODULE , ONLY : PRIOR_PAR, DIST
  USE MODEL_CONST_MOD, ONLY : NPAR
  IMPLICIT NONE
  
  INTEGER, INTENT(IN) :: SIZEPAR
  INTEGER , INTENT(IN) :: MC    
  REAL(DP), INTENT(IN) ,  DIMENSION(SIZEPAR, SIZEPAR) :: SIGMA_DRAWS  
  REAL(DP), INTENT(IN) ,  DIMENSION(SIZEPAR) :: PARINI
  REAL(DP), INTENT(IN) :: C_SCALE
  INTEGER , INTENT(OUT) :: ACCEPT
  REAL(DP), DIMENSION(MC, SIZEPAR) :: DRAWS

  !! WORKING VARIABLES 
  INTEGER I,INFO,j
  REAL(DP) OLDF, NEWF, U
  REAL(DP), DIMENSION(SIZEPAR) :: MEAN  
  REAL(DP), DIMENSION(SIZEPAR) :: THETA_NEW, THETA_OLD  
  REAL(DP), DIMENSION(SIZEPAR, SIZEPAR) :: SIGMA 
  LOGICAL OK_DRAW
  REAL(DP) RATF
  integer check_bonds
  external CHECK_BONDS

  !SIGMA = C_SCALE*SIGMA_DRAWS
  SIGMA = SIGMA_DRAWS
  !INCLUIR PARBOUDS
  ACCEPT = 0
  CALL ESTIMATEOBJ(SIZEPAR,PARINI,OLDF)  
  print *,"aqui voy"
  THETA_OLD = PARINI
  DO I = 1, MC      
     if (mod(I, 10) .eq. 0) then 
        write(*,'(a5, i10, a10, f15.5)') 'iter', i, 'accept', dble(accept)/dble(i)
     end if
     OK_DRAW = .TRUE.
     DO WHILE (OK_DRAW)         
        CALL RMNDRAWS(SIZEPAR, THETA_OLD, SIGMA, THETA_NEW, INFO)
!        do j=1,SIZEPAR
!           print *,"THETA",j,THETA_new(J)
! 	ENDDO                    
 !       print *,  CHECK_BONDS(THETA_NEW, SIZEPAR,PARBOUNDS)
 !       IF ( CHECK_BONDS(THETA_NEW, SIZEPAR,PARBOUNDS) .EQ. 0 ) THEN    
!            !CHECK_BONDS(PAR, SIZEPAR,PARBOUDS)       
           OK_DRAW = .FALSE.
 !       END IF
     END DO
     !PRINT *, THETA_NEW
     
     CALL ESTIMATEOBJ(SIZEPAR,THETA_NEW,NEWF)
   !  print *,"NEWF=",NEWF
     CALL RANDOM_NUMBER(U)    
     !PRINT *, "NEWF=",NEWF,"OLDF=",OLDF,"U=",U
     RATF=EXP(-NEWF+OLDF)
     !PRINT*,"RATF=",RATF
     IF ( RATF .GE. U ) THEN !REVISAR (EXP(-NEWF)/EXP(-OLDF)) ES UNA MALA IDEA
        THETA_OLD = THETA_NEW
        OLDF = NEWF 
        ACCEPT = ACCEPT + 1
     END IF
     !PRINT *, THETA_OLD
     DRAWS(I, 1:SIZEPAR) = THETA_OLD     
  END DO
  RETURN  
END SUBROUTINE MCMCMODEL
