MODULE HYBRID_CONST_MOD
  INTEGER NEQ, NMC, NT, NSTEP, IPRINT, NUMTRYS 
  DOUBLE PRECISION T0, RHO
  DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: BL, BU
END MODULE HYBRID_CONST_MOD

MODULE MODEL_CONST_MOD
  INTEGER NPAR, NUM_N, NUM_K, NUM_EXO, NUM_OBS, NUM_CNTRL_OBS, NUM_EST_OBS, NUM_EST, NUM_PER, NUM_RAT_OBS, ESTIMSIZE
  INTEGER NUM_PAR_EST, NUM_VAR_EST
END MODULE MODEL_CONST_MOD

MODULE LIKELIHOOD_CONST_MOD
  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(12, 60) 
  REAL(DP), DIMENSION(:, :), ALLOCATABLE:: Y
  REAL(DP), DIMENSION(:, :), ALLOCATABLE ::  P_INI 
  REAL(DP), DIMENSION(:), ALLOCATABLE :: A_INI, CONS_OBS
  REAL(DP), ALLOCATABLE, DIMENSION(:) :: RATMEAN, RATWEIGHT
  INTEGER, ALLOCATABLE, DIMENSION(:) :: ZIND, EXOIND, RATIND, VAREXOIND 
  INTEGER,  DIMENSION(:,:), ALLOCATABLE :: Z
  REAL(DP) RAT_ERROR
  REAL(DP) ,  ALLOCATABLE, DIMENSION(:) :: RAT_OBS
 ! integer , parameter :: sizepar=2
END MODULE LIKELIHOOD_CONST_MOD

MODULE XINI_MOD
  IMPLICIT NONE 
  DOUBLE PRECISION , DIMENSION(:), ALLOCATABLE :: XINI   
END MODULE XINI_MOD
  
MODULE PARAMETER_VECTOR_MOD
  IMPLICIT NONE
  DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE:: PARVECTOR, VARVECTOR, MEDIDAMEAN_CTRL, MEDIDAVAR_CTRL
  DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE:: MEDIDAMEAN_EXO, MEDIDAVAR_EXO
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE:: PARBOUNDS
  INTEGER, DIMENSION(:), ALLOCATABLE:: PARIND
END MODULE PARAMETER_VECTOR_MOD

MODULE PRIOR_MODULE
  IMPLICIT NONE
  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(12, 60)  
  REAL(DP), DIMENSION(:,:) , ALLOCATABLE :: PRIOR_PAR
  CHARACTER(LEN=4), ALLOCATABLE  :: DIST(:) 
  
  
END MODULE PRIOR_MODULE
