MODULE PARAMETERS_MOD
  IMPLICIT NONE
  INTEGER, PARAMETER  :: DP = SELECTED_REAL_KIND(12, 60)
  REAL(DP) ALFA,ALFAV,CSTAR_BAR,EPSCD,EPSE,EPSM,EPSQ,EPSRM,EPST,EPSW,EPSXD,ETA_M,FBAR,GAMA,&
       &GAMA_CD,GAMA_E,GAMA_M,GAMA_X,GAMA_XD,GBAR,HAB,ISTAR,MU,NBAR,OMEG_S,OMEG_U,OMEGA,OMEGA_CD,&
       &OMEGA_E,OMEGA_M,OMEGA_X,OMEGA_XD,PI_BAR,PI_STAR_BAR,PIB_BAR,PSI_1,PSI_ADJCOST_C,PSI_ADJCOST_X,&
       &PSI_X,QM_BAR,QMR_BAR,RHO_CSTAR,RHO_G,RHO_I,RHO_PI,RHO_PI_STAR,RHO_QM,RHO_QMR,RHO_TR,RHO_Y,&
       &RHO_Z_XDEMAND,RHO_ZCD,RHO_ZD,RHO_ZE,RHO_ZH,RHO_ZI,RHO_ZIE,RHO_ZM,RHO_ZNT,RHO_ZQ,RHO_ZRM,RHO_ZU,&
       &RHO_ZX,RHO_ZXD,RHOQ,RHOQV,SIGMA_M,TBP,TD,THETA,THETA_CD,THETA_E,THETA_M,THETA_RM,THETA_T,&
       &THETA_W,THETA_XD,TR_BAR,UPSILON,V,VC,VE,VN,VNT,VR,VX,Z_XDEMAND_BAR,ZCD_BAR,ZD_BAR,ZE_BAR,&
       &ZH_BAR,ZI_BAR,ZIE_BAR,ZM_BAR,ZNT_BAR,ZQ_BAR,ZRM_BAR,ZU_BAR,ZX_BAR,ZXD_BAR


END MODULE PARAMETERS_MOD



SUBROUTINE PASSPAR(PARVECTOR,NPAR)
  USE  PARAMETERS_MOD
  IMPLICIT NONE
  !INTEGER, PARAMETER  :: DP = SELECTED_REAL_KIND(14, 60)
  INTEGER NPAR
  REAL(DP) , DIMENSION(NPAR) :: PARVECTOR

  !PARAMETERS GET IN AS A COMMONN BLOCKS
  REAL(DP)  BETTA,BETTASTAR,PSI_2
 

  ALFA =PARVECTOR(1)
  ALFAV =PARVECTOR(2)
  CSTAR_BAR =PARVECTOR(3)
  EPSCD =PARVECTOR(7) !PARVECTOR(4)
  EPSE =PARVECTOR(5)
  EPSM =PARVECTOR(6)
  EPSQ =PARVECTOR(7)
  EPSRM =PARVECTOR(8)
  EPST =PARVECTOR(9)
  EPSW =PARVECTOR(10)
  EPSXD =PARVECTOR(7) !PARVECTOR(11)
  ETA_M =PARVECTOR(12)
  FBAR =PARVECTOR(13)
  GAMA =PARVECTOR(14)
  GAMA_CD =PARVECTOR(15)
  GAMA_E =PARVECTOR(16)
  GAMA_M =PARVECTOR(17)
  GAMA_X =PARVECTOR(18)
  GAMA_XD =PARVECTOR(19)
  GBAR =PARVECTOR(20)
  HAB =PARVECTOR(21)
  ISTAR =PARVECTOR(22)
  MU =PARVECTOR(23)
  NBAR =PARVECTOR(24)
  OMEG_S =PARVECTOR(25)
  OMEG_U =PARVECTOR(26)
  OMEGA =PARVECTOR(27)
  OMEGA_CD =PARVECTOR(28)
  OMEGA_E =PARVECTOR(29)
  OMEGA_M =PARVECTOR(30)
  OMEGA_X =PARVECTOR(31)
  OMEGA_XD =PARVECTOR(32)
  PI_BAR =PARVECTOR(33)
  PI_STAR_BAR =PARVECTOR(34)
  PIB_BAR =PARVECTOR(35)
  PSI_1 =PARVECTOR(36)
  PSI_ADJCOST_C =PARVECTOR(37)
  PSI_ADJCOST_X =PARVECTOR(38)
  PSI_X =PARVECTOR(39)
  QM_BAR =PARVECTOR(40)
  QMR_BAR =PARVECTOR(41)
  RHO_CSTAR =PARVECTOR(42)
  RHO_G =PARVECTOR(43)
  RHO_I =PARVECTOR(44)
  RHO_PI =PARVECTOR(45)
  RHO_PI_STAR =PARVECTOR(46)
  RHO_QM =PARVECTOR(47)
  RHO_QMR =PARVECTOR(48)
  RHO_TR =PARVECTOR(49)
  RHO_Y =PARVECTOR(50)
  RHO_Z_XDEMAND =PARVECTOR(51)
  RHO_ZCD =PARVECTOR(52)
  RHO_ZD =PARVECTOR(53)
  RHO_ZE =PARVECTOR(54)
  RHO_ZH =PARVECTOR(55)
  RHO_ZI =PARVECTOR(56)
  RHO_ZIE =PARVECTOR(57)
  RHO_ZM =PARVECTOR(58)
  RHO_ZNT =PARVECTOR(59)
  RHO_ZQ =PARVECTOR(60)
  RHO_ZRM =PARVECTOR(61)
  RHO_ZU =PARVECTOR(62)
  RHO_ZX =PARVECTOR(63)
  RHO_ZXD =PARVECTOR(64)
  RHOQ =PARVECTOR(65)
  RHOQV =PARVECTOR(66)
  SIGMA_M =PARVECTOR(67)
  TBP =PARVECTOR(68)
  TD =PARVECTOR(69)
  THETA =PARVECTOR(70)
  THETA_CD =PARVECTOR(71)
  THETA_E =PARVECTOR(72)
  THETA_M =PARVECTOR(73)
  THETA_RM =PARVECTOR(74)
  THETA_T =PARVECTOR(75)
  THETA_W =PARVECTOR(76)
  THETA_XD =PARVECTOR(77)
  TR_BAR =PARVECTOR(78)
  UPSILON =PARVECTOR(79)
  V =PARVECTOR(80)
  VC =PARVECTOR(81)
  VE =PARVECTOR(82)
  VN =PARVECTOR(83)
  VNT =PARVECTOR(84)
  VR =PARVECTOR(85)
  VX =PARVECTOR(86)
  Z_XDEMAND_BAR =PARVECTOR(87)
  ZCD_BAR =PARVECTOR(88)
  ZD_BAR =PARVECTOR(89)
  ZE_BAR =PARVECTOR(90)
  ZH_BAR =PARVECTOR(91)
  ZI_BAR =PARVECTOR(92)
  ZIE_BAR =PARVECTOR(93)
  ZM_BAR =PARVECTOR(94)
  ZNT_BAR =PARVECTOR(95)
  ZQ_BAR =PARVECTOR(96)
  ZRM_BAR =PARVECTOR(97)
  ZU_BAR =PARVECTOR(98)
  ZX_BAR =PARVECTOR(99)
  ZXD_BAR =PARVECTOR(100)

  !DEFINE BETTA AND PHI_1 
  BETTASTAR  = (PI_STAR_BAR)/(ISTAR)
  BETTA  =  BETTASTAR*(1+GBAR)**(SIGMA_M)
  PSI_2  = ((1+UPSILON)/UPSILON)*((1-BETTA*(1+GBAR)**(-SIGMA_M)*(1-PSI_1))/(BETTA*(1+GBAR)**(-SIGMA_M)))

 ! print *,"ZXD_BAR",ZXD_BAR

END SUBROUTINE PASSPAR
