SUBROUTINE RMNDRAWS(N, MEAN, SIGMA, DEVIATES, INFO)
  USE RANDOM
  ! SIGMA COVARAINZA
  ! MEAN MEDIA
  ! DEVIATES : (N X 1) DEV = MEAN + SIGMA*SD_NORMAL  
  !INFO .NE.0 SI HAY PROBLEMAS EN LA CHOLESKY
  IMPLICIT NONE 
  
  INTEGER, INTENT(IN) :: N
  REAL(DP) , DIMENSION(N, N), INTENT(IN) :: SIGMA
  REAL(DP) , DIMENSION(N), INTENT(IN) :: MEAN
  REAL(DP) , DIMENSION(N), INTENT(OUT) :: DEVIATES
  INTEGER , INTENT(OUT) :: INFO
  REAL(DP) , DIMENSION(N,1)  :: DRAWS  
  REAL(DP) , DIMENSION(N, N) :: CSIGMA
  INTEGER I

  CSIGMA = SIGMA  
  DO I = 1, N
     DRAWS(I,1) = RANDOM_NORMAL()
  END DO
  DEVIATES = MEAN        
  CALL DSYMV('L',INT(N),DBLE(1.0),CSIGMA,INT(N),DRAWS,INT(1),DBLE(1.0),DEVIATES,INT(1))

END SUBROUTINE RMNDRAWS
