SUBROUTINE RTDRAWS(N, MEAN, V, SIGMA, DEVIATES, INFO)
  USE RANDOM
  IMPLICIT NONE  
  INTEGER, INTENT(IN) :: N  
  REAL(DP) , DIMENSION(N, N), INTENT(IN) :: SIGMA
  REAL(DP) , DIMENSION(N), INTENT(IN) :: MEAN
  REAL(DP) , DIMENSION(N), INTENT(OUT) :: DEVIATES
  INTEGER , INTENT(IN) :: V
  REAL(DP) , DIMENSION(N):: DRAWS
  REAL(DP) , DIMENSION(N, N) :: CSIGMA
  REAL(DP) X

  INTEGER INFO , I 
  LOGICAL FIRST

  CSIGMA = SIGMA  
  CALL DPOTRF( 'L', INT(N), CSIGMA, INT(N), INFO )  
  IF ( INFO .EQ. 0 ) THEN 
     DO I = 1, N
        DRAWS(I) = RANDOM_NORMAL()      
     END DO
     CALL DSYMV('L',INT(N),DBLE(1.0),CSIGMA,INT(N),DRAWS,INT(1),DBLE(0.0),DEVIATES,INT(1))          
     FIRST= .TRUE.
     X = RANDOM_CHISQ(V, FIRST) 
     DEVIATES = MEAN + DEVIATES/DBLE(SQRT(X/DBLE((V - 2.0_DP))))
     FIRST = .FALSE. 
  END IF

END SUBROUTINE RTDRAWS
