SUBROUTINE SIMUL_AB(PARVECTOR, XINI, AMAT, BMAT)
  USE RANDOM
  USE HYBRID_CONST_MOD
  USE MODEL_CONST_MOD

  IMPLICIT NONE
  ! NUM_OBS=NUM_CNTRL_OBS + NUM_EST_OBS
  !integer, parameter :: NUM_K=53
  DOUBLE PRECISION BST
  INTEGER INFO
  integer i, j

  !DOUBLE PRECISION, DIMENSION(NUM_OBS, NUM_OBS) :: M_P0
  
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NPAR) :: PARVECTOR 
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(NEQ) :: XINI
  DOUBLE PRECISION, INTENT(OUT), DIMENSION(NUM_N,NUM_N) :: AMAT, BMAT
  DOUBLE PRECISION, DIMENSION(NUM_N)  :: SSVAL

  DOUBLE PRECISION, DIMENSION(NUM_N-NUM_K,NUM_K)  :: F
  DOUBLE PRECISION, DIMENSION(NUM_K,NUM_K)  :: P

  EXTERNAL SOLVESS, GETSTEADYSTATE, ABMATRIX

   
     
  !!PARAMETER VALUES
    
  CALL PASSPAR(PARVECTOR,NPAR)
  CALL SOLVESS(PARVECTOR,NPAR, XINI, BST,INFO )
  IF ( ( INFO .NE. 0 ) ) then    
      print *, "NO SE PUEDE ENCONTRAR EL SS"
     RETURN
  END IF
!   print *, bst
!   PRINT *, 'XINI'
!   DO I = 1, SIZE(XINI)
!      PRINT '(A, I2,A,F10.5)','XINI(', I, ')=', XINI(I)
!   END DO

  CALL GETSTEADYSTATE(XINI, NEQ, SSVAL,  NUM_N)

  open(1, file='ssval.txt')
  do i = 1, NUM_N
     write (1, '(f20.15)') SSVAL(i)
  end do
  close(1)


!      DO I = 1, SIZE(SSVAL)
!         PRINT '(A, I3,A,f14.7)','SSVAL(', I, ')=', SSVAL(I)
!      END DO
  CALL ABMATRIX(NUM_N, AMAT, BMAT, log(SSVAL))

 CALL AIM(AMAT,BMAT,NUM_N,NUM_K,INT(1),INT(1),F,P,INFO)     
  IF (INFO .NE. 0) THEN
     PRINT *, 'AIM no llego'
     CALL DSOLAB(F, P, AMAT, BMAT, NUM_N, NUM_K, INFO)  
     PRINT *,"AQUI VOY 0"
     PRINT *,"info=",info
     !IF ( INFO .NE. 0 ) THEN
     !END IF
  ENDIF

 ! AMAT=DBLE(0.0)
 ! BMAT=DBLE(0.0)

 PRINT *,"YA LO HICE" 

END SUBROUTINE SIMUL_ab
