ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	1
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	2
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	3
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	4
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	5
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	6
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	7
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	8
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	9
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	10
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	11
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	12
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	13
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	14
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	15
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	16
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	17
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	18
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	19
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	20
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	21
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	22
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	23
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	24
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	25
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	26
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	27
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	28
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	29
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	30
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	31
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	32
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	33
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	34
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	35
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	36
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	37
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	38
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	39
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	40
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	41
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	42
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	43
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	44
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	45
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	46
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	47
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	48
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	49
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	50
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	51
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	52
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	53
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	54
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	55
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	56
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	57
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	58
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	59
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	60
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	61
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	62
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	63
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	64
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	65
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	66
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	67
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	68
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	69
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	70
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	71
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	72
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	73
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	74
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	75
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	76
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	77
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	78
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	79
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	80
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	81
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	82
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	83
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	84
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	85
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	86
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	87
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	88
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	89
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	90
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	91
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	92
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	93
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	94
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	95
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	96
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	97
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	98
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	99
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	100
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	101
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	102
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	103
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	104
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	105
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	106
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	107
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	108
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	109
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	110
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	111
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	112
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	113
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	114
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	115
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	116
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	117
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	118
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	119
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	120
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	121
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	122
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	123
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	124
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	125
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	126
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	127
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	128
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	129
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	130
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	131
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	132
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	133
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	134
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	135
