ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	101
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	102
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	103
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	104
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	105
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	106
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	107
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	108
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	109
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	110
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	111
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	112
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	113
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	114
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	115
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	116
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	117
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	118
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	119
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	120
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	121
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	122
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	123
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	124
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	125
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	126
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	127
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	128
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	129
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	130
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	131
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	132
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	133
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	134
ts ./patacon_bayes.out 135 par_final.csv xini_final.csv	135
