SUBROUTINE HYBRIDSA_EST(FUNOBJ,NUMPAR,BL,BU,T0,NT,NMC,RHO,NSTEP,PARAMIN,POINTS)
 ! USE HYBRID_CONST_MOD
  IMPLICIT NONE
  INTEGER, INTENT(IN) ::  NUMPAR,NT,NMC,NSTEP
  DOUBLE PRECISION, INTENT(IN) :: T0,RHO    
  DOUBLE PRECISION, INTENT(IN),DIMENSION (NUMPAR) :: BL,BU,PARAMIN    
  INTEGER ::  NP
  DOUBLE PRECISION, INTENT(OUT) ,DIMENSION(NUMPAR, INT(2)) :: POINTS
  
  
  DOUBLE PRECISION, DIMENSION(NUMPAR) :: PARAM, EPSI, INBL, INBU , DPARAM  
!  DOUBLE PRECISION, DIMENSION(NUMPAR,2) :: PARBOUNDS
  DOUBLE PRECISION BST,DIFF,NEWOBJ,OBJF, P, U, T
  INTEGER I,I1,I2,INFO !,CHECK_BONDS

  EXTERNAL FUNIDRAW, MINVECT, MAXVECT,HIBPRINT !, CHECK_BONDS
  EXTERNAL FUNOBJ, RNDSTART,RNDEND
  INTEGER ACCEPT, ISCAPE
  LOGICAL FLAG

!  BST = 1E10
 CALL FUNOBJ(NUMPAR,PARAMIN,BST)

  POINTS = 0.0
  POINTS(:,1)=PARAMIN
  !     INITIALISE THE TEMPERATURE  
  T = T0
  EPSI = (BU-BL)/NSTEP

  FLAG = .TRUE.
  ISCAPE = 0

! PARBOUNDS(:,1)=BL
! PARBOUNDS(:,2)=BU
! DO I=1,NUMPAR
!    PRINT *,BL(I), PARAMIN(I), BU(I)
! ENDDO
! PRINT *, "check:",CHECK_BONDS(PARAMIN, NUMPAR,PARBOUNDS)
  
!  DO WHILE (FLAG .EQV. .TRUE. )
!     CALL FUNIDRAW(BL, BU, NUMPAR, PARAM) 
!!   PRINT *, "**********************************************************" 
!!   DO I=1,NUMPAR
!!     PRINT *,BL(I), PARAM(I), BU(I)
!!   ENDDO
! 
!     CALL FUNOBJ(NUMPAR,PARAM,OBJF)  
!     PRINT *,"OBJF=",OBJF   
!          !ESTIMATEOBJ(ESTIMSIZE,PAR,LOG_L)
!     FLAG = ISNAN(OBJF)          
!  END DO

  CALL FUNOBJ(NUMPAR,PARAMIN,OBJF)
  FLAG = .TRUE.
!  PRINT *, OBJF
  PARAM=PARAMIN
  DO I1 = 1,NT         
    ! NP = 1
     ACCEPT  = 0
     
     DO  I2 = 1,NMC
        PRINT *,"I2:",I2
!        POINTS(1:NUMPAR,  (NP+1)) = PARAM
        POINTS(1:NUMPAR, 2) = PARAM
        CALL MAXVECT((POINTS(1:NUMPAR,2) - EPSI(1:NUMPAR)),BL,NUMPAR, INBL)
        CALL MINVECT((POINTS(1:NUMPAR,2) +EPSI(1:NUMPAR)),BU,NUMPAR, INBU)
        
        !DPARAM = PARAM
        DO WHILE (FLAG .EQV. .TRUE. )           
           CALL FUNIDRAW(INBL, INBU, NUMPAR, PARAM)            
           CALL FUNOBJ(NUMPAR,PARAM,NEWOBJ)
         !  PRINT *,"NEWOBJ:",NEWOBJ
          !    DO I=1,NUMPAR
          !       PRINT *,BL(I), PARAM(I), BU(I)
          !    ENDDO
           FLAG = ISNAN(NEWOBJ)
        !   PRINT *,FLAG
        END DO
        !PRINT *, NEWOBJ
        !PARAM = DPARAM        
        FLAG = .TRUE.
        
        DIFF = (NEWOBJ-OBJF)
        
        IF (DIFF.LT.0.0) THEN
           ACCEPT = ACCEPT +1
           !NP = NP + 1               
           POINTS(1:NUMPAR, 2) = PARAM
           
           OBJF = NEWOBJ
           IF (NEWOBJ.LT.BST) THEN
              BST = NEWOBJ
              POINTS(1:NUMPAR, 1) = PARAM
           END IF
           
        ELSE
           
           P = EXP(-DIFF/T)               
           CALL FUNIDRAW(DBLE(0.0), DBLE(1.0), INT(1.0), U )
           IF (U.LT.P) THEN
            !  NP = NP + 1
              ACCEPT = ACCEPT +1
              OBJF = NEWOBJ
              POINTS(1:NUMPAR, 2) = PARAM
           ELSE
              PARAM(1:NUMPAR) = POINTS(1:NUMPAR,2)
           END IF
        END IF
      ! PRINT *,"I2:",I2 
     ENDDO
    ! IF ( MOD(I1, 100 ) .EQ. 0 ) THEN 
    !    CALL HIBPRINT(T, I1, DBLE(ACCEPT)/DBLE(NMC), BST, OBJF)!, NP)
    ! END IF
     
     PRINT *,"TEMPERATURE STEP:",I1   
     PRINT *,"TEMPERATURE:",T
     PRINT *,"ACCEPTANCE RATE:",ACCEPT
     PRINT *,"CURRENT VALUE:",OBJF
     PRINT *,"BEST VALUE:",BST    
     T = T*RHO 


     
  END DO
  

  RETURN
END SUBROUTINE HYBRIDSA_EST
   
   
!SUBROUTINE MAXVECT(X, Y,N, NEWX)
!  IMPLICIT NONE
!  INTEGER N, I
!  DOUBLE PRECISION X(N,1), Y(N,1), NEWX(N,1)      
!
!  DO I = 1, N         
!     IF (X(I,1).LE.Y(I,1) ) THEN
!        NEWX(I,1) = Y(I,1)
!     ELSE
!        NEWX(I,1) = X(I,1)
!     END IF
!
!  END DO
!  RETURN
!END SUBROUTINE MAXVECT
!
!SUBROUTINE MINVECT(X, Y,N, NEWX)
!  IMPLICIT NONE
!  INTEGER N, I
!  DOUBLE PRECISION X(N,1), Y(N,1), NEWX(N,1)      
!
!  DO I = 1, N         
!     IF (X(I,1).LE.Y(I,1) ) THEN
!        NEWX(I,1) = X(I,1)
!     ELSE
!        NEWX(I,1) = Y(I,1)
!     END IF
!  END DO
!  RETURN
!END SUBROUTINE MINVECT


!SUBROUTINE FUNIDRAW(LB, UB, K, DRAWS )
!  !USE RANDOM_UNIFORM
!  IMPLICIT NONE
!  
!  INTEGER K,I
!  DOUBLE PRECISION LB(K), UB(K), DRAWS(K)
!  double precision tmp
!  !EXTERNAL UNIDRAW
!!  CALL RANDOM_NUMBER()
!
!  DO I =1, K
!     CALL RANDOM_NUMBER(tmp)
!     DRAWS(I) = LB(I)  + (UB(I) - LB(I))*tmp !tmp RANDOM_UNIFORM(REAL(LB(I)), REAL(UB(I)))
!  ENDDO
!
!END SUBROUTINE FUNIDRAW


SUBROUTINE HIBPRINT(TEMP, TEMSTEP, ACCEPT, BEST, CURRENT)!, NP )  
  IMPLICIT NONE 
  
  INTEGER, INTENT(IN) :: TEMSTEP !, NP 
  DOUBLE PRECISION, INTENT(IN) :: TEMP, BEST, CURRENT , ACCEPT
  PRINT * 
  PRINT '(A16, I10, A11, F10.5)', "TEMPERATURE STEP",TEMSTEP,"TEMPERATURE" ,TEMP 
  PRINT '(A14,F10.5)', "ACCEPTACE RATE", ACCEPT 
 ! PRINT '(A24, I5)', "NUMBER OF INITIAL VALUES", NP 
  PRINT '(A26, F10.5)', "CURRENT OBJECTIVE FUNCTION", CURRENT 
  PRINT '(A13, F10.5)', "BEST FUNCTION" ,BEST 
  PRINT *
  
END SUBROUTINE
  

