SUBROUTINE SIMULMODEL(PARVECTOR, VARVECTOR, XINI, A_INI, YSIM, ASIM)
  USE RANDOM
  USE HYBRID_CONST_MOD
  USE MODEL_CONST_MOD, ONLY: NPAR, NUM_N, NUM_K, NUM_EXO, NUM_CNTRL_OBS, NUM_EST_OBS, NUM_EST, NUM_PER, NUM_RAT_OBS
  USE LIKELIHOOD_CONST_MOD, ONLY : ZIND, EXOIND
  
  IMPLICIT NONE
  ! NUM_OBS=NUM_CNTRL_OBS + NUM_EST_OBS
  DOUBLE PRECISION BST
  INTEGER INFO
  integer i, j
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EST) :: M_T
  DOUBLE PRECISION, DIMENSION(NUM_EST,NUM_EXO) :: M_R

  !DOUBLE PRECISION, DIMENSION(NUM_OBS, NUM_OBS) :: M_P0
  DOUBLE PRECISION, DIMENSION(NUM_CNTRL_OBS + NUM_EST_OBS, NUM_EST) :: M_Z
  DOUBLE PRECISION, DIMENSION(NUM_EXO, NUM_PER) :: ETA
  DOUBLE PRECISION, DIMENSION(NUM_CNTRL_OBS + NUM_EST_OBS, NUM_PER) :: ET
  DOUBLE PRECISION, DIMENSION(NUM_CNTRL_OBS + NUM_EST_OBS,NUM_CNTRL_OBS + NUM_EST_OBS) :: M_H
  DOUBLE PRECISION, DIMENSION(NUM_EXO,NUM_EXO) :: M_Q
  
  DOUBLE PRECISION, INTENT(OUT) ,DIMENSION(NUM_CNTRL_OBS + NUM_EST_OBS, NUM_PER)::  YSIM
  DOUBLE PRECISION, INTENT(OUT) , DIMENSION(NUM_EST, NUM_PER+1) :: ASIM 
  
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NPAR) :: PARVECTOR 
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EXO) :: VARVECTOR 
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(NEQ) :: XINI
  
  DOUBLE PRECISION, DIMENSION(NUM_N-NUM_K,NUM_K) :: F
  DOUBLE PRECISION, DIMENSION(NUM_K,NUM_K) :: P
  DOUBLE PRECISION, DIMENSION(NUM_N,NUM_N) :: AMAT, BMAT
  DOUBLE PRECISION, DIMENSION(NUM_N)  :: SSVAL
  DOUBLE PRECISION, DIMENSION(NUM_RAT_OBS)  :: RAT_OBS
  DOUBLE Precision LOG_L
 ! EXTERNAL SOLVESS, GETSTEADYSTATE, ABMATRIX, DSOLAB, AIM
 ! EXTERNAL KALMANSIMUL
 ! EXTERNAL KALMANFILTERMATRICES
    
  DOUBLE PRECISION, INTENT(IN), DIMENSION(NUM_EST) ::A_INI
  REAL (dp),  DIMENSION(NUM_CNTRL_OBS,NUM_K) :: F_OBS

     

  !!PARAMETER VALUES
    
  CALL PASSPAR(PARVECTOR,NPAR)
  CALL SOLVESS(PARVECTOR,NPAR, XINI, BST,INFO )
  IF ( ( INFO .NE. 0 ) ) then    
      print *, "SIMULMODEL: NO SE PUEDE ENCONTRAR EL SS"
     RETURN
  END IF
!   print *, bst
!   PRINT *, 'XINI'
!   DO I = 1, SIZE(XINI)
!      PRINT '(A, I2,A,F10.5)','XINI(', I, ')=', XINI(I)
!   END DO
  !CALL GETSTEADYSTATE(XINI, NEQ, SSVAL,  NUM_N)
  CALL GETSTEADYSTATE(XINI, NEQ, SSVAL, NUM_N, NUM_RAT_OBS, RAT_OBS)
  open(1, file='ssval.txt')
  do i = 1, NUM_N
     write (1, '(f20.15)') SSVAL(i)
  end do
  close(1)


!      DO I = 1, SIZE(SSVAL)
!         PRINT '(A, I3,A,f14.7)','SSVAL(', I, ')=', SSVAL(I)
!      END DO
  CALL ABMATRIX(NUM_N, AMAT, BMAT, log(SSVAL))
  !CALL AIM(AMAT,BMAT,NUM_N,NUM_K,INT(1),INT(1),F,P,INFO)     
  !IF (INFO .NE. 0) THEN
  !PRINT *, 'AIM no llegó'
  CALL DSOLAB(F, P, AMAT, BMAT, NUM_N, NUM_K, INFO)  
  IF ( INFO .NE. 0 ) THEN
     LOG_L = -1.0
     LOG_L = sqrt(LOG_L)
     RETURN
  END IF
  !ENDIF
!   CALL DSOLAB(F, P, AMAT, BMAT, NUM_N, NUM_K, INFO) 

  CALL OBSCONTROLKALMAN(F,F_OBS)
  
  CALL KALMANFILTERMATRICES(F_OBS, P, NUM_K, NUM_EXO, NUM_CNTRL_OBS,M_R, M_T)
!  PRINT *, "AQUI"
  !! ERROR DE MEDIDA
  !print *, any(ISNAN(YSIM))
  M_H = 0.0
  DO I = 1, NUM_CNTRL_OBS + NUM_EST_OBS
     M_H(I,I) = 1.0E-12     
  ENDDO

  !! ESTADOS INICIALES DEL FILTRO DE KALMAN 
  
  M_Q = 0.0
  DO I = 1, NUM_EXO
     M_Q(I,I) = VARVECTOR(I)
     !print *,"Q=",Q(I,I)
  ENDDO 
  
  M_Z = 0.0  
 
  DO I=1, NUM_CNTRL_OBS
     M_Z(I,I) = 1.0
  ENDDO


  IF (NUM_EST_OBS>0) THEN
     DO I=NUM_CNTRL_OBS+1,NUM_CNTRL_OBS+NUM_EST_OBS
        M_Z(I,NUM_CNTRL_OBS+EXOIND(I-NUM_CNTRL_OBS))= 1.0
     ENDDO
  END IF  


  DO I = 1, NUM_PER
     DO J = 1, NUM_EXO
        ETA(J,I)  = RANDOM_NORMAL()
        ! ETA(J,I)  =0.0
     END DO
  END DO
 ! ETA(6,1)  =1.0
  !Error de medida
  ET = 0.0  
  CALL KALMANSIMUL(M_Z,M_T,M_H,M_R,M_Q, A_INI, ET, ETA, NUM_PER,NUM_CNTRL_OBS + NUM_EST_OBS, NUM_EST, NUM_EXO, YSIM, ASIM, INFO )
    !   KALMANSIMUL(  Z,  T,  H,  R,  Q, A0,    ET, ETA, NDIM,   PDIM,                        MDIM,    RDIM,    Y,     A,   INFO )
!  CALL KALMANSIMUL(M_Z,M_T,M_H,M_R,M_Q, A_INI, ET, ETA, NUM_PER,NUM_OBS, NUM_N, NUM_EXO, YSIM, ASIM, INFO )
  
  OPEN (1,FILE="YSIMMAT.txt" )
  DO J = 1, NUM_PER
     DO I = 1, NUM_CNTRL_OBS + NUM_EST_OBS
        write (1, '(ES14.7)'), YSIM(I,J) 
   !     write(1,'(1X,200f10.5)') (AMAT(i,j),j=1,UBOUND(AMAT, 2)) 
     END DO
  END DO
  CLOSE(1)
  

END SUBROUTINE SIMULMODEL
