SUBROUTINE WRHBRD(XINI, NEQ, FVEC, INFO)
  USE Solve_NonLin
  IMPLICIT NONE 
  
  INTEGER, INTENT(OUT) :: INFO  
  INTEGER, INTENT(in) :: NEQ
  DOUBLE PRECISION, INTENT(INOUT), DIMENSION(NEQ) :: XINI
  DOUBLE PRECISION, intent(out) , DIMENSION(NEQ)  ::  FVEC
  
  !!Constantes de convergencia
  INTEGER, PARAMETER:: LONG = SELECTED_REAL_KIND(9,99)
  DOUBLE PRECISION, PARAMETER ::  TOL = 0.5*sqrt(EPSILON(1.0_long))
  DOUBLE PRECISION, PARAMETER :: EPSFCN = EPSILON(1.0_LONG)  
  DOUBLE PRECISION, ALLOCATABLE ::  WA(:)  
  INTEGER LWA
  DOUBLE PRECISION, DIMENSION(NEQ) :: X   

  EXTERNAL FCNHYD
  
  LWA = INT(CEILING(real( 2.0*((neq*(neq+13))/2.0) )))
  ALLOCATE(WA(LWA))
  WA = 1.0

  X = XINI
  CALL HBRD(FCNHYD, NEQ, X, FVEC, EPSFCN, TOL, INFO, WA)  
  XINI = X
  DEALLOCATE(WA)
  
END SUBROUTINE WRHBRD


SUBROUTINE WRCSOLVE(XINI, NEQ, FVEC, INFO)
 ! USE CSOLVE_MOD
  IMPLICIT NONE
  INTEGER, INTENT(IN) ::NEQ
  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(14,60) 
  REAL(DP), PARAMETER :: CRIT = 0.0001_DP*SQRT(EPSILON(1.0_DP))
  REAL(DP), INTENT(INOUT) ,DIMENSION(NEQ) :: XINI
  INTEGER , PARAMETER :: ITMAX = 700
  INTEGER INFO
  REAL(DP), INTENT(OUT),  DIMENSION(NEQ) :: FVEC
  LOGICAL, PARAMETER :: VERBOSE= .FALSE. 
  DOUBLE PRECISION, DIMENSION(NEQ) :: X  
  
  EXTERNAL FCNHYD
  X = XINI
 ! CALL CSOLVEF90(FCNHYD,XINI,NEQ,CRIT,ITMAX, VERBOSE, INFO)    
  CALL FCNHYD(NEQ,XINI,FVEC,INFO)  
  XINI = X
  
END SUBROUTINE WRCSOLVE
