# NB: this file was automatically generated by Dynare
#     from qpm_simpl1.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(10, 11);
gp = zeros(10, 10, 11);
end
return (rp, gp)
end
